from enum import StrEnum
class MemoryType(StrEnum):
    FACT='FACT'; OBSERVATION='OBSERVATION'; DECISION='DECISION'; INTERVENTION='INTERVENTION'; OUTCOME='OUTCOME'; RELATIONSHIP='RELATIONSHIP'; CONTRADICTION='CONTRADICTION'; HYPOTHESIS='HYPOTHESIS'; LESSON='LESSON'; EVIDENCE='EVIDENCE'
