"""initial TRACE schema"""
from alembic import op
import sqlalchemy as sa
revision='0001_initial_trace'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('feedback',sa.Column('id',sa.String(36),primary_key=True),sa.Column('source',sa.String(40),nullable=False),sa.Column('source_external_id',sa.String(120)),sa.Column('customer_id',sa.String(120)),sa.Column('product_id',sa.String(120)),sa.Column('product_version',sa.String(80)),sa.Column('timestamp',sa.DateTime(),nullable=False),sa.Column('text',sa.Text(),nullable=False),sa.Column('rating',sa.Float()),sa.Column('sentiment',sa.String(30)),sa.Column('language',sa.String(12),nullable=False),sa.Column('metadata',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('source','source_external_id',name='uq_feedback_source_external'))
    op.create_index('ix_feedback_timestamp','feedback',['timestamp']); op.create_index('ix_feedback_product','feedback',['product_id']); op.create_index('ix_feedback_customer','feedback',['customer_id'])
    op.create_table('problems',sa.Column('id',sa.String(36),primary_key=True),sa.Column('canonical_title',sa.String(200),nullable=False),sa.Column('canonical_description',sa.Text(),nullable=False),sa.Column('problem_type',sa.String(80),nullable=False),sa.Column('product_area',sa.String(100),nullable=False),sa.Column('severity',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('first_seen_at',sa.DateTime(),nullable=False),sa.Column('last_seen_at',sa.DateTime(),nullable=False),sa.Column('occurrence_count',sa.Integer(),nullable=False),sa.Column('current_sentiment',sa.Float(),nullable=False),sa.Column('historical_sentiment_summary',sa.JSON(),nullable=False),sa.Column('customer_segments',sa.JSON(),nullable=False),sa.Column('current_state',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False))
    op.create_index('ix_problem_last_seen','problems',['last_seen_at']); op.create_index('ix_problem_status','problems',['status'])
    op.create_table('decisions',sa.Column('id',sa.String(36),primary_key=True),sa.Column('problem_id',sa.String(36),sa.ForeignKey('problems.id',ondelete='CASCADE'),nullable=False),sa.Column('decision',sa.Text(),nullable=False),sa.Column('rationale',sa.Text(),nullable=False),sa.Column('decision_maker',sa.String(120)),sa.Column('timestamp',sa.DateTime(),nullable=False))
    op.create_table('interventions',sa.Column('id',sa.String(36),primary_key=True),sa.Column('problem_id',sa.String(36),sa.ForeignKey('problems.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(200),nullable=False),sa.Column('why',sa.Text(),nullable=False),sa.Column('target_segment',sa.String(120)),sa.Column('target_platform',sa.String(80)),sa.Column('expected_outcome',sa.Text(),nullable=False),sa.Column('timestamp',sa.DateTime(),nullable=False),sa.Column('decision_maker',sa.String(120)),sa.Column('status',sa.String(40),nullable=False))
    op.create_table('outcomes',sa.Column('id',sa.String(36),primary_key=True),sa.Column('intervention_id',sa.String(36),sa.ForeignKey('interventions.id',ondelete='CASCADE'),nullable=False),sa.Column('outcome_type',sa.String(40),nullable=False),sa.Column('qualitative_evidence',sa.Text(),nullable=False),sa.Column('metric',sa.JSON(),nullable=False),sa.Column('measurement_window_days',sa.Integer()),sa.Column('timestamp',sa.DateTime(),nullable=False))
    op.create_index('ix_outcome_intervention','outcomes',['intervention_id'])
    op.create_table('evidence',sa.Column('id',sa.String(36),primary_key=True),sa.Column('source_type',sa.String(50),nullable=False),sa.Column('source_id',sa.String(120),nullable=False),sa.Column('evidence_type',sa.String(50),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('timestamp',sa.DateTime(),nullable=False),sa.Column('relevance',sa.Float(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False))
    op.create_index('ix_evidence_source','evidence',['source_id'])
    op.create_table('relationships',sa.Column('id',sa.String(36),primary_key=True),sa.Column('from_problem_id',sa.String(36),sa.ForeignKey('problems.id',ondelete='CASCADE'),nullable=False),sa.Column('to_problem_id',sa.String(36),sa.ForeignKey('problems.id',ondelete='CASCADE'),nullable=False),sa.Column('relation_type',sa.String(40),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('evidence',sa.JSON(),nullable=False))
    op.create_table('analysis_audits',sa.Column('id',sa.String(36),primary_key=True),sa.Column('operation',sa.String(80),nullable=False),sa.Column('input_text',sa.Text(),nullable=False),sa.Column('model',sa.String(120),nullable=False),sa.Column('prompt_version',sa.String(80),nullable=False),sa.Column('retrieved_memories',sa.JSON(),nullable=False),sa.Column('evidence_ids',sa.JSON(),nullable=False),sa.Column('output_json',sa.JSON(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('timestamp',sa.DateTime(),nullable=False),sa.Column('request_id',sa.String(64)))
    op.create_table('memory_records',sa.Column('id',sa.String(36),primary_key=True),sa.Column('memory_type',sa.String(40),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.JSON(),nullable=False),sa.Column('hindsight_id',sa.String(160)),sa.Column('is_stale',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False))
    op.create_table('evaluation_runs',sa.Column('id',sa.String(36),primary_key=True),sa.Column('scenario_id',sa.String(120),nullable=False),sa.Column('results',sa.JSON(),nullable=False),sa.Column('score',sa.Float(),nullable=False),sa.Column('timestamp',sa.DateTime(),nullable=False))

def downgrade():
    for name in ['evaluation_runs','memory_records','analysis_audits','relationships','evidence','outcomes','interventions','decisions','problems','feedback']: op.drop_table(name)
